# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\KundeForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KundeForm(object):
    def setupUi(self, KundeForm):
        KundeForm.setObjectName("KundeForm")
        KundeForm.resize(454, 305)
        self.formLayout = QtWidgets.QFormLayout(KundeForm)
        self.formLayout.setObjectName("formLayout")
        self.label_kundename = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_kundename.setFont(font)
        self.label_kundename.setObjectName("label_kundename")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_kundename)
        self.lineEdit_kunde = QtWidgets.QLineEdit(KundeForm)
        self.lineEdit_kunde.setObjectName("lineEdit_kunde")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_kunde)
        self.line = QtWidgets.QFrame(KundeForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line)
        self.label_Consultant = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Consultant.setFont(font)
        self.label_Consultant.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Consultant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Consultant.setObjectName("label_Consultant")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_Consultant)
        self.lineEdit_consultant = QtWidgets.QLineEdit(KundeForm)
        self.lineEdit_consultant.setObjectName("lineEdit_consultant")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_consultant)
        self.label_senior = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_senior.setFont(font)
        self.label_senior.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_senior.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_senior.setObjectName("label_senior")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_senior)
        self.lineEdit_senior = QtWidgets.QLineEdit(KundeForm)
        self.lineEdit_senior.setObjectName("lineEdit_senior")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_senior)
        self.label_chief = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_chief.setFont(font)
        self.label_chief.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_chief.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_chief.setObjectName("label_chief")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_chief)
        self.lineEdit_chief = QtWidgets.QLineEdit(KundeForm)
        self.lineEdit_chief.setObjectName("lineEdit_chief")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_chief)
        self.label_travel = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_travel.setFont(font)
        self.label_travel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_travel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_travel.setObjectName("label_travel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_travel)
        self.lineEdit_travel = QtWidgets.QLineEdit(KundeForm)
        self.lineEdit_travel.setObjectName("lineEdit_travel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_travel)
        self.label_rabatt = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_rabatt.setFont(font)
        self.label_rabatt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_rabatt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rabatt.setObjectName("label_rabatt")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_rabatt)
        self.lineEdit_rabatt = QtWidgets.QLineEdit(KundeForm)
        self.lineEdit_rabatt.setObjectName("lineEdit_rabatt")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_rabatt)
        self.label_km = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_km.setFont(font)
        self.label_km.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_km.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_km.setObjectName("label_km")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_km)
        self.lineEdit_km = QtWidgets.QLineEdit(KundeForm)
        self.lineEdit_km.setObjectName("lineEdit_km")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_km)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 9, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_save = QtWidgets.QPushButton(KundeForm)
        self.Button_save.setObjectName("Button_save")
        self.horizontalLayout.addWidget(self.Button_save)
        self.Button_left = QtWidgets.QPushButton(KundeForm)
        self.Button_left.setObjectName("Button_left")
        self.horizontalLayout.addWidget(self.Button_left)
        self.Button_right = QtWidgets.QPushButton(KundeForm)
        self.Button_right.setObjectName("Button_right")
        self.horizontalLayout.addWidget(self.Button_right)
        self.Button_cancel = QtWidgets.QPushButton(KundeForm)
        self.Button_cancel.setObjectName("Button_cancel")
        self.horizontalLayout.addWidget(self.Button_cancel)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_timeprisfor = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_timeprisfor.setFont(font)
        self.label_timeprisfor.setObjectName("label_timeprisfor")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_timeprisfor)
        self.label_avtale = QtWidgets.QLabel(KundeForm)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_avtale.setFont(font)
        self.label_avtale.setObjectName("label_avtale")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_avtale)
        self.lineEdit_avtale = QtWidgets.QLineEdit(KundeForm)
        self.lineEdit_avtale.setObjectName("lineEdit_avtale")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_avtale)
        self.Button_nykunde = QtWidgets.QPushButton(KundeForm)
        self.Button_nykunde.setEnabled(False)
        self.Button_nykunde.setObjectName("Button_nykunde")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.Button_nykunde)

        self.retranslateUi(KundeForm)
        QtCore.QMetaObject.connectSlotsByName(KundeForm)
        KundeForm.setTabOrder(self.lineEdit_kunde, self.lineEdit_consultant)
        KundeForm.setTabOrder(self.lineEdit_consultant, self.lineEdit_senior)
        KundeForm.setTabOrder(self.lineEdit_senior, self.lineEdit_chief)
        KundeForm.setTabOrder(self.lineEdit_chief, self.lineEdit_avtale)
        KundeForm.setTabOrder(self.lineEdit_avtale, self.lineEdit_travel)
        KundeForm.setTabOrder(self.lineEdit_travel, self.lineEdit_rabatt)
        KundeForm.setTabOrder(self.lineEdit_rabatt, self.lineEdit_km)
        KundeForm.setTabOrder(self.lineEdit_km, self.Button_save)
        KundeForm.setTabOrder(self.Button_save, self.Button_left)
        KundeForm.setTabOrder(self.Button_left, self.Button_right)
        KundeForm.setTabOrder(self.Button_right, self.Button_cancel)

    def retranslateUi(self, KundeForm):
        _translate = QtCore.QCoreApplication.translate
        KundeForm.setWindowTitle(_translate("KundeForm", "Kunde form"))
        self.label_kundename.setText(_translate("KundeForm", "Kunde name:"))
        self.label_Consultant.setText(_translate("KundeForm", "Consultant :"))
        self.label_senior.setText(_translate("KundeForm", "Senior Consultant :"))
        self.label_chief.setText(_translate("KundeForm", "Chief Consultant :"))
        self.label_travel.setText(_translate("KundeForm", "Travel :"))
        self.label_rabatt.setText(_translate("KundeForm", "Rabatt :"))
        self.label_km.setText(_translate("KundeForm", "KM :"))
        self.Button_save.setText(_translate("KundeForm", "Save"))
        self.Button_left.setText(_translate("KundeForm", "<"))
        self.Button_right.setText(_translate("KundeForm", ">"))
        self.Button_cancel.setText(_translate("KundeForm", "Cancel"))
        self.label_timeprisfor.setText(_translate("KundeForm", "Time pris for"))
        self.label_avtale.setText(_translate("KundeForm", "Avtale :"))
        self.Button_nykunde.setText(_translate("KundeForm", "Ny kunde"))
