# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RegTimer.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import qdarkstyle

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 452)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.button_view = QtWidgets.QPushButton(self.centralwidget)
        self.button_view.setObjectName("button_view")
        self.verticalLayout_7.addWidget(self.button_view)
        self.button_rigth = QtWidgets.QPushButton(self.centralwidget)
        self.button_rigth.setObjectName("button_rigth")
        self.verticalLayout_7.addWidget(self.button_rigth)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 2, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_3.addWidget(self.calendarWidget, 0, 6, 1, 1)
        self.progressBar_regCSMS = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_regCSMS.setFont(font)
        self.progressBar_regCSMS.setProperty("value", 24)
        self.progressBar_regCSMS.setObjectName("progressBar_regCSMS")
        self.gridLayout_3.addWidget(self.progressBar_regCSMS, 14, 6, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_kr_ar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_kr_ar.setFont(font)
        self.label_kr_ar.setObjectName("label_kr_ar")
        self.gridLayout_4.addWidget(self.label_kr_ar, 1, 0, 1, 1)
        self.label_kr_mnd = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_kr_mnd.setFont(font)
        self.label_kr_mnd.setObjectName("label_kr_mnd")
        self.gridLayout_4.addWidget(self.label_kr_mnd, 2, 0, 1, 1)
        self.label_kr_dag = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_kr_dag.setFont(font)
        self.label_kr_dag.setObjectName("label_kr_dag")
        self.gridLayout_4.addWidget(self.label_kr_dag, 3, 0, 1, 1)
        self.label_sum_ar = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_sum_ar.setFont(font)
        self.label_sum_ar.setObjectName("label_sum_ar")
        self.gridLayout_4.addWidget(self.label_sum_ar, 1, 1, 1, 1)
        self.label_sum_mnd = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_sum_mnd.setFont(font)
        self.label_sum_mnd.setObjectName("label_sum_mnd")
        self.gridLayout_4.addWidget(self.label_sum_mnd, 2, 1, 1, 1)
        self.label_sum_dag = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_sum_dag.setFont(font)
        self.label_sum_dag.setObjectName("label_sum_dag")
        self.gridLayout_4.addWidget(self.label_sum_dag, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 11, 6, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Ordrenr = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Ordrenr.setFont(font)
        self.label_Ordrenr.setObjectName("label_Ordrenr")
        self.gridLayout_2.addWidget(self.label_Ordrenr, 1, 0, 1, 1)
        self.comboBox_ratecard = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ratecard.setObjectName("comboBox_ratecard")
        self.gridLayout_2.addWidget(self.comboBox_ratecard, 3, 2, 1, 1)
        self.lineEdit_timepris = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_timepris.setObjectName("lineEdit_timepris")
        self.gridLayout_2.addWidget(self.lineEdit_timepris, 4, 2, 1, 1)
        self.label_kunde = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_kunde.setFont(font)
        self.label_kunde.setObjectName("label_kunde")
        self.gridLayout_2.addWidget(self.label_kunde, 0, 0, 1, 1)
        self.comboBox_ordrenr = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ordrenr.setObjectName("comboBox_ordrenr")
        self.gridLayout_2.addWidget(self.comboBox_ordrenr, 1, 2, 1, 1)
        self.comboBox_kunde = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_kunde.sizePolicy().hasHeightForWidth())
        self.comboBox_kunde.setSizePolicy(sizePolicy)
        self.comboBox_kunde.setObjectName("comboBox_kunde")
        self.gridLayout_2.addWidget(self.comboBox_kunde, 0, 2, 1, 1)
        self.checkBox_overtid = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_overtid.setFont(font)
        self.checkBox_overtid.setObjectName("checkBox_overtid")
        self.gridLayout_2.addWidget(self.checkBox_overtid, 5, 3, 1, 1)
        self.label_timepris = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_timepris.setFont(font)
        self.label_timepris.setObjectName("label_timepris")
        self.gridLayout_2.addWidget(self.label_timepris, 4, 0, 1, 1)
        self.label_overtid = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_overtid.setFont(font)
        self.label_overtid.setObjectName("label_overtid")
        self.gridLayout_2.addWidget(self.label_overtid, 5, 0, 1, 1)
        self.label_category = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_category.setFont(font)
        self.label_category.setObjectName("label_category")
        self.gridLayout_2.addWidget(self.label_category, 2, 0, 1, 1)
        self.comboBox_category = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_category.setObjectName("comboBox_category")
        self.gridLayout_2.addWidget(self.comboBox_category, 2, 2, 1, 1)
        self.label_ratecard = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ratecard.setFont(font)
        self.label_ratecard.setObjectName("label_ratecard")
        self.gridLayout_2.addWidget(self.label_ratecard, 3, 0, 1, 1)
        self.comboBox_overtid = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_overtid.setObjectName("comboBox_overtid")
        self.gridLayout_2.addWidget(self.comboBox_overtid, 5, 2, 1, 1)
        self.label_antalltimer = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_antalltimer.setFont(font)
        self.label_antalltimer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_antalltimer.setObjectName("label_antalltimer")
        self.gridLayout_2.addWidget(self.label_antalltimer, 6, 0, 1, 1)
        self.doubleSpinBox_antalltimer = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_antalltimer.setObjectName("doubleSpinBox_antalltimer")
        self.gridLayout_2.addWidget(self.doubleSpinBox_antalltimer, 6, 2, 1, 1)
        self.checkBox_timerregistrert = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_timerregistrert.setFont(font)
        self.checkBox_timerregistrert.setObjectName("checkBox_timerregistrert")
        self.gridLayout_2.addWidget(self.checkBox_timerregistrert, 6, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 4, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setObjectName("button_clear")
        self.verticalLayout_6.addWidget(self.button_clear)
        self.button_left = QtWidgets.QPushButton(self.centralwidget)
        self.button_left.setObjectName("button_left")
        self.verticalLayout_6.addWidget(self.button_left)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.label_notat = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_notat.setFont(font)
        self.label_notat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_notat.setObjectName("label_notat")
        self.gridLayout_3.addWidget(self.label_notat, 11, 2, 1, 1)
        self.textEdit_notat = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_notat.setObjectName("textEdit_notat")
        self.gridLayout_3.addWidget(self.textEdit_notat, 11, 4, 1, 1)
        self.progressBar_time_reg = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_time_reg.setFont(font)
        self.progressBar_time_reg.setProperty("value", 24)
        self.progressBar_time_reg.setObjectName("progressBar_time_reg")
        self.gridLayout_3.addWidget(self.progressBar_time_reg, 12, 6, 1, 1)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setObjectName("button_save")
        self.gridLayout_3.addWidget(self.button_save, 16, 0, 1, 1)
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setEnabled(False)
        self.button_delete.setObjectName("button_delete")
        self.gridLayout_3.addWidget(self.button_delete, 16, 2, 1, 1)
        self.label_timer_reg = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_timer_reg.setFont(font)
        self.label_timer_reg.setObjectName("label_timer_reg")
        self.gridLayout_3.addWidget(self.label_timer_reg, 12, 5, 1, 1)
        self.label_regCSMS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_regCSMS.setFont(font)
        self.label_regCSMS.setObjectName("label_regCSMS")
        self.gridLayout_3.addWidget(self.label_regCSMS, 14, 5, 1, 1)
        self.label_arbeids_timer_tilgjengelig_p_valgt_dag = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_arbeids_timer_tilgjengelig_p_valgt_dag.sizePolicy().hasHeightForWidth())
        self.label_arbeids_timer_tilgjengelig_p_valgt_dag.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_arbeids_timer_tilgjengelig_p_valgt_dag.setFont(font)
        self.label_arbeids_timer_tilgjengelig_p_valgt_dag.setObjectName("label_arbeids_timer_tilgjengelig_p_valgt_dag")
        self.gridLayout_3.addWidget(self.label_arbeids_timer_tilgjengelig_p_valgt_dag, 16, 6, 1, 1)
        self.label_arbeids_timer_dag = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_arbeids_timer_dag.setFont(font)
        self.label_arbeids_timer_dag.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_arbeids_timer_dag.setObjectName("label_arbeids_timer_dag")
        self.gridLayout_3.addWidget(self.label_arbeids_timer_dag, 16, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 21))
        self.menubar.setObjectName("menubar")
        self.menuMeny = QtWidgets.QMenu(self.menubar)
        self.menuMeny.setObjectName("menuMeny")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVis_resultat = QtWidgets.QAction(MainWindow)
        self.actionVis_resultat.setObjectName("actionVis_resultat")
        self.actionVis_timer = QtWidgets.QAction(MainWindow)
        self.actionVis_timer.setObjectName("actionVis_timer")
        self.actionVis_Legg_til_kunder = QtWidgets.QAction(MainWindow)
        self.actionVis_Legg_til_kunder.setObjectName("actionVis_Legg_til_kunder")
        self.actionHent_overtid_liste = QtWidgets.QAction(MainWindow)
        self.actionHent_overtid_liste.setObjectName("actionHent_overtid_liste")
        self.menuMeny.addAction(self.actionVis_timer)
        self.menuMeny.addAction(self.actionVis_resultat)
        self.menuMeny.addAction(self.actionVis_Legg_til_kunder)
        self.menuMeny.addAction(self.actionHent_overtid_liste)
        self.menubar.addAction(self.menuMeny.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_clear, self.button_view)
        MainWindow.setTabOrder(self.button_view, self.button_left)
        MainWindow.setTabOrder(self.button_left, self.button_rigth)
        MainWindow.setTabOrder(self.button_rigth, self.comboBox_kunde)
        MainWindow.setTabOrder(self.comboBox_kunde, self.comboBox_ordrenr)
        MainWindow.setTabOrder(self.comboBox_ordrenr, self.comboBox_category)
        MainWindow.setTabOrder(self.comboBox_category, self.comboBox_ratecard)
        MainWindow.setTabOrder(self.comboBox_ratecard, self.lineEdit_timepris)
        MainWindow.setTabOrder(self.lineEdit_timepris, self.comboBox_overtid)
        MainWindow.setTabOrder(self.comboBox_overtid, self.checkBox_overtid)
        MainWindow.setTabOrder(self.checkBox_overtid, self.doubleSpinBox_antalltimer)
        MainWindow.setTabOrder(self.doubleSpinBox_antalltimer, self.checkBox_timerregistrert)
        MainWindow.setTabOrder(self.checkBox_timerregistrert, self.textEdit_notat)
        MainWindow.setTabOrder(self.textEdit_notat, self.button_save)
        MainWindow.setTabOrder(self.button_save, self.button_delete)
        MainWindow.setTabOrder(self.button_delete, self.calendarWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_view.setText(_translate("MainWindow", "View is off"))
        self.button_rigth.setText(_translate("MainWindow", ">"))
        self.label_kr_ar.setText(_translate("MainWindow", "Kr År :"))
        self.label_kr_mnd.setText(_translate("MainWindow", "Kr mnd :"))
        self.label_kr_dag.setText(_translate("MainWindow", "Kr dag :"))
        self.label_sum_ar.setText(_translate("MainWindow", "TextLabel"))
        self.label_sum_mnd.setText(_translate("MainWindow", "TextLabel"))
        self.label_sum_dag.setText(_translate("MainWindow", "TextLabel"))
        self.label_Ordrenr.setText(_translate("MainWindow", "Ordre nr :"))
        self.label_kunde.setText(_translate("MainWindow", "Kunde :"))
        self.checkBox_overtid.setText(_translate("MainWindow", "Overtid levert"))
        self.label_timepris.setText(_translate("MainWindow", "Timepris :"))
        self.label_overtid.setText(_translate("MainWindow", "Overtid :"))
        self.label_category.setText(_translate("MainWindow", "Category :"))
        self.label_ratecard.setText(_translate("MainWindow", "Rate card :"))
        self.label_antalltimer.setText(_translate("MainWindow", "Antall Timer :"))
        self.checkBox_timerregistrert.setText(_translate("MainWindow", "Timer Registrert"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))
        self.button_left.setText(_translate("MainWindow", "<"))
        self.label_notat.setText(_translate("MainWindow", " Notat :"))
        self.button_save.setText(_translate("MainWindow", "Save"))
        self.button_delete.setText(_translate("MainWindow", "Delete"))
        self.label_timer_reg.setText(_translate("MainWindow", "% timer reg :"))
        self.label_regCSMS.setText(_translate("MainWindow", "% reg i CSMS :"))
        self.label_arbeids_timer_tilgjengelig_p_valgt_dag.setText(_translate("MainWindow", "arbeids timer tilgjengelig på valgt dag"))
        self.label_arbeids_timer_dag.setText(_translate("MainWindow", "8"))
        self.menuMeny.setTitle(_translate("MainWindow", "Meny"))
        self.actionVis_resultat.setText(_translate("MainWindow", "Vis resultat"))
        self.actionVis_timer.setText(_translate("MainWindow", "Vis timer"))
        self.actionVis_Legg_til_kunder.setText(_translate("MainWindow", "Vis/Legg til  kunder"))
        self.actionHent_overtid_liste.setText(_translate("MainWindow", "Hent overtid liste"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet(qt_api='pyqt5'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
