# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ShowOvertid.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowOvertid(object):
    def setupUi(self, ShowOvertid):
        ShowOvertid.setObjectName("ShowOvertid")
        ShowOvertid.resize(1330, 764)
        self.verticalLayout = QtWidgets.QVBoxLayout(ShowOvertid)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(ShowOvertid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(13)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_Save = QtWidgets.QPushButton(ShowOvertid)
        self.Button_Save.setObjectName("Button_Save")
        self.horizontalLayout.addWidget(self.Button_Save)
        self.Button_Cancel = QtWidgets.QPushButton(ShowOvertid)
        self.Button_Cancel.setObjectName("Button_Cancel")
        self.horizontalLayout.addWidget(self.Button_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ShowOvertid)
        QtCore.QMetaObject.connectSlotsByName(ShowOvertid)

    def retranslateUi(self, ShowOvertid):
        _translate = QtCore.QCoreApplication.translate
        ShowOvertid.setWindowTitle(_translate("ShowOvertid", "Overtid"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ShowOvertid", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ShowOvertid", "dato"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ShowOvertid", "kunde"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ShowOvertid", "ordrenr"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ShowOvertid", "category"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ShowOvertid", "rate_card"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ShowOvertid", "overtid"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ShowOvertid", "timer"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ShowOvertid", "timepris"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("ShowOvertid", "notes"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("ShowOvertid", "registrert"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("ShowOvertid", "overtidlevert"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("ShowOvertid", "uke"))
        self.Button_Save.setText(_translate("ShowOvertid", "Save"))
        self.Button_Cancel.setText(_translate("ShowOvertid", "Cancel"))
