# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ShowTimer.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showtimer(object):
    def setupUi(self, showtimer):
        showtimer.setObjectName("showtimer")
        showtimer.resize(1326, 749)
        self.gridLayout = QtWidgets.QGridLayout(showtimer)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(showtimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_ukenr = QtWidgets.QSpinBox(showtimer)
        self.spinBox_ukenr.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.spinBox_ukenr.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBox_ukenr.setObjectName("spinBox_ukenr")
        self.horizontalLayout.addWidget(self.spinBox_ukenr)
        self.label_2 = QtWidgets.QLabel(showtimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_sqlquery = QtWidgets.QLineEdit(showtimer)
        self.lineEdit_sqlquery.setObjectName("lineEdit_sqlquery")
        self.horizontalLayout.addWidget(self.lineEdit_sqlquery)
        self.pushButton_save = QtWidgets.QPushButton(showtimer)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_cancel = QtWidgets.QPushButton(showtimer)
        self.pushButton_cancel.setEnabled(False)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.dateEdit = QtWidgets.QDateEdit(showtimer)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(showtimer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(13)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.retranslateUi(showtimer)
        QtCore.QMetaObject.connectSlotsByName(showtimer)

    def retranslateUi(self, showtimer):
        _translate = QtCore.QCoreApplication.translate
        showtimer.setWindowTitle(_translate("showtimer", "Show Timer"))
        self.label.setText(_translate("showtimer", "Uke nr :"))
        self.label_2.setText(_translate("showtimer", "SQLite spørring :"))
        self.pushButton_save.setText(_translate("showtimer", "Save"))
        self.pushButton_cancel.setText(_translate("showtimer", "Cancel"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("showtimer", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("showtimer", "dato"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("showtimer", "kunde"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("showtimer", "ordrenr"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("showtimer", "category"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("showtimer", "rate_card"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("showtimer", "overtid"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("showtimer", "timer"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("showtimer", "timepris"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("showtimer", "notes"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("showtimer", "registrert"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("showtimer", "overtidlevert"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("showtimer", "uke"))
